- name: VPS configuration
  hosts: all
  gather_facts: false
  become: true
  vars:
    local_user: "{{ VPS_USERNAME }}"
    ansible_user: "{{ local_user }}"

  roles:
    - role: user-setup
    - role: vps-config
    - role: auto-reboot
      when: AUTO_REBOOT is defined
    - role: docker
      when: SKIP_DOCKER_INSTALL is not defined
