- name: VPS configuration
  hosts: all
  gather_facts: false
  become: true
  vars:
    local_user: "{{ VPS_USERNAME }}"
    ansible_user: "{{ local_user }}"

  roles:
    - role: user-setup
    - role: vps-config
