---
- name: Configure UFW
  block:
    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow some ports
      community.general.ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.protocol }}"
      with_items:
        - { 'port': 22, 'protocol': tcp, 'rule': limit }
        - { 'port': 443, 'protocol': tcp, 'rule': allow }

    - name: Set UFW to default deny
      community.general.ufw:
        policy: deny

    - name: Unattended-upgrades config
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/50unattended-upgrades"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { 'regexp': '^.*Unattended-Upgrade::Remove-Unused-Kernel-Packages*', 'line': 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";' }
        - { 'regexp': '^.*Unattended-Upgrade::Remove-New-Unused-Dependencies*', 'line': 'Unattended-Upgrade::Remove-New-Unused-Dependencies "true";' }
        - { 'regexp': '^.*Unattended-Upgrade::Automatic-Reboot*', 'line': 'Unattended-Upgrade::Automatic-Reboot "false";' }
