- name: Create new user
  ansible.builtin.user:
    name: "{{ local_user }}"
    state: present
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true

- name: Enable passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/100-local-users
    content: |
      {{ local_user }} ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: '0400'

- name: Setup SSH keys
  ansible.builtin.copy:
    src: ./ssh_files/
    dest: "/home/{{ local_user }}/.ssh/"
    mode: '0700'
    owner: "{{ local_user }}"

- name: Configure authorized keys
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    remote_src: true
    dest: "/home/{{ local_user }}/.ssh/"
    mode: '0600'
    owner: "{{ local_user }}"

- name: Update SSHD config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^PermitRootLogin*', line: 'PermitRootLogin=no' }
    - { regexp: '^AllowUsers*', line: 'AllowUsers {{ local_user }}' }
    - { regexp: '^PasswordAuthentication*', line: 'PasswordAuthentication no' }
    - { regexp: '^PubkeyAuthentication*', line: 'PubkeyAuthentication yes' }
  notify:
    - Restart_ssh
