- name: My first play
  hosts: "{{ env | default('dev') }}"
  tasks:

    - name: Print apt output
      ansible.builtin.debug:
        msg: "Print output"

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - nginx
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - python3.10-venv
      register: result
      retries: 5
      delay: 30
      until: result.failed == false

    - name: Configure UFW to allow SSH
      community.general.ufw:
        state: enabled
        default: allow
        name: OpenSSH

    - name: Configure UFW to allow HTTP
      community.general.ufw:
        state: enabled
        default: allow
        name: 'Nginx Full'

    - name: Copy over SSH keys for github auth
      ansible.builtin.copy:
        src: ../ssh_files/
        dest: ~/.ssh/
        owner: root
        group: root
        mode: '0700'

    - name: Clone all the project Github repos
      ansible.builtin.git:
        repo: "git@github.com:shanetwinterhalter/{{ item }}.git"
        dest: "~/{{ item }}"
        depth: 1
      loop: "{{ projects }}"
