- name: VPS configuration
  hosts: "{{ env | default('dev') }}"
  vars:
    install_dir: /srv
  tasks:

    - name: Print output
      ansible.builtin.debug:
        msg: "Print output"

    - name: Run initial setup
      ansible.builtin.include_tasks: init.yaml
      vars:
        hosting_env: "{{ env | default('dev') }}"
      when: install_type == "full"

    - name: Configure projects
      ansible.builtin.include_tasks: projects.yaml
      loop: "{{ (project_update is defined and project_update) | ternary(projects | selectattr('project_name', 'equalto', project_update) | list, projects) }}"
      loop_control:
        loop_var: project
      when: (install_type == "full") or (install_type == "update")

    # Configure certificates
    - name: Configure certificates
      ansible.builtin.include_tasks: certs.yaml
      vars:
        letsencrypt_dir: /etc/letsencrypt
        cert_cn: "{{ cert_common_name }}"
        cert_san: "DNS:{{ cert_subj_alt_names | join(',DNS:') }}"
        acme_directory: "{{ letsencrypt_server }}"
        force_cert_update: "{{ cert_update | default('false') }}"
      when: (install_type == "full") or (install_type == "certs")
