- name: Install docker pre-requisites
  ansible.builtin.apt:
    name:
      - 'ca-certificates'
      - 'curl'
    update_cache: true
    state: 'present'

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: 'directory'
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Add docker repo apt key
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    dest: '/etc/apt/keyrings/docker.asc'
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Get ansible_distribution_release if we don't have it
  ansible.builtin.gather_facts:
  when: ansible_distribution_release is not defined

- name: Add docker repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: 'present'
    filename: 'docker'

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-buildx-plugin'
      - 'docker-compose-plugin'
    update_cache: true
    state: 'present'

- name: Add local user to docker group
  ansible.builtin.user:
    name: "{{ local_user }}"
    groups: 'docker'
    append: true

- name: Configure docker daemon
  ansible.builtin.copy:
    dest: '/etc/docker/daemon.json'
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Enable docker
  ansible.builtin.service:
    name: 'docker'
    state: 'started'
    enabled: true
